name: build hello-world service
on:
  push:
    paths:
      - "src/docker/helloworld/**"
      - ".github/**"
  workflow_dispatch:

jobs:
  build-hello-world-service:
    name: build Hello World service
    runs-on: ubuntu-latest
    container: docker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        
      - name: Build and push docker image
        env:
          REGISTRY_TOKEN: ${{secrets.GHCR_TOKEN}}
          REGISTRY_URL: ghcr.io/manuelottlik
          IMAGE_NAME: hello-world-service
          IMAGE_TAG: latest
        run: |
          cd src/hello-world-service
          docker login -u publisher -p $REGISTRY_TOKEN $REGISTRY_URL
          docker build -t $REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG .
          docker push $REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG
