name: build latex pdf
on: [push]

jobs:
  build_latex:
    name: build latex pdf
    runs-on: ubuntu-latest
    steps:
      - name: set up git repository
        uses: actions/checkout@v2

      - name: compile latex document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: tex
          root_file: main.tex

      - name: upload pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: tex/main.pdf